"""create_master_vulnerabilities_table

Revision ID: 24dcea9b4f96
Revises: a4b81ab029aa
Create Date: 2026-08-06 14:55:39.521216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24dcea9b4f96'
down_revision: Union[str, Sequence[str], None] = 'a4b81ab029aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_vulnerabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('cvss_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('cvss_vector', sa.String(length=255), nullable=True),
    sa.Column('cwe', sa.String(length=50), nullable=True),
    sa.Column('owasp', sa.String(length=100), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('ai_prompt', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_vulnerabilities_id'), 'master_vulnerabilities', ['id'], unique=False)
    op.create_index(op.f('ix_master_vulnerabilities_title'), 'master_vulnerabilities', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_vulnerabilities_title'), table_name='master_vulnerabilities')
    op.drop_index(op.f('ix_master_vulnerabilities_id'), table_name='master_vulnerabilities')
    op.drop_table('master_vulnerabilities')
    # ### end Alembic commands ###
