"""add_caption_and_original_filename_to_evidence

Revision ID: 8db762743927
Revises: 192d2da8cddd
Create Date: 2026-08-07 09:44:24.489038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8db762743927'
down_revision: Union[str, Sequence[str], None] = '192d2da8cddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finding_evidence', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.add_column('finding_evidence', sa.Column('caption', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finding_evidence', 'caption')
    op.drop_column('finding_evidence', 'original_filename')
    # ### end Alembic commands ###
