"""make_assigned_to_nullable

Revision ID: a4b81ab029aa
Revises: bf0ccbef8274
Create Date: 2026-08-06 14:26:32.757217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4b81ab029aa'
down_revision: Union[str, Sequence[str], None] = 'bf0ccbef8274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'assigned_to',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'assigned_to',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
